In [6]:
from keras.models import load_model

In [7]:
model = load_model('arrow_detection.h5')

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 98, 98, 64)        1792      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 49, 49, 64)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 47, 47, 64)        36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 23, 23, 64)       0         
 2D)                                                             
                                                                 
 flatten (Flatten)           (None, 33856)             0         
                                                                 
 dense (Dense)               (None, 128)               4

In [13]:
import cv2
import numpy as np

In [17]:
cam=cv2.VideoCapture(0)
while True:
    _,frame=cam.read()
    raw = cv2.resize(frame,(100,100))
    raw = raw/255
    li = [raw]
    li = np.array(li)
    print(model.predict(li))
    cv2.imshow("Video",frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cam.release()
cv2.destroyAllWindows()


[[0.03070541 0.9692946 ]]
[[0.04968004 0.95031995]]
[[0.3265456  0.67345434]]
[[0.09844328 0.9015567 ]]
[[0.03821508 0.9617849 ]]
[[0.02784695 0.9721531 ]]
[[0.01494877 0.9850513 ]]
[[0.01802993 0.9819701 ]]
[[0.03912947 0.9608705 ]]
[[0.28428817 0.71571183]]
[[0.3923279 0.6076721]]
[[0.38898337 0.61101663]]
[[0.21249579 0.7875042 ]]
[[0.13565882 0.86434114]]
[[0.23043716 0.76956284]]
[[0.22645599 0.77354395]]
[[0.1092591  0.89074093]]
[[0.06693292 0.9330671 ]]
[[0.01138487 0.98861516]]
[[0.00578151 0.99421847]]
[[1.1732587e-04 9.9988270e-01]]
[[8.117227e-05 9.999188e-01]]
[[4.0493429e-05 9.9995947e-01]]
[[1.05176205e-05 9.99989510e-01]]
[[4.0236541e-06 9.9999595e-01]]
[[4.5042275e-06 9.9999547e-01]]
[[3.1869024e-06 9.9999678e-01]]
[[3.5001735e-06 9.9999654e-01]]
[[5.9039353e-06 9.9999404e-01]]
[[7.4208137e-06 9.9999261e-01]]
[[6.8932655e-05 9.9993110e-01]]
[[8.6343236e-05 9.9991369e-01]]
[[3.6642395e-04 9.9963355e-01]]
[[4.1007536e-04 9.9958998e-01]]
[[9.5263729e-04 9.9904734e-01]]
[[